### ISSUE TITLE
Select input to wide when importing actions

### ISSUE THREAD

**Issue by jensborje** [zetkin/organize.zetk.in#1030] opened 2019-11-11 10:58 UTC
The select input in when importing actions are to wide.

![Screen Shot 2019-11-11 at 11 39 53](https://user-images.githubusercontent.com/1271517/68581210-3c270c00-0478-11ea-8791-69255cae8366.png)

Steps to reproduce:
- Go to https://organize.zetk.in/campaign/actions
- Click on the button "Import actions" in the top right corner
- Add a xlsx-file following the instructions in the pane. Make sure that one field, like location, doesn't exist in the organization.

**Comment by richardolsson** [comment] 2019-11-11 12:03
Duplicate of #1004, which was recently fixed.

**Closed by richardolsson** 2019-11-11 12:03 UTC
Labels: bug, enhancement
