### ISSUE TITLE
Survey list can't handle empty list

### ISSUE THREAD

**Issue by jensborje** [zetkin/organize.zetk.in#461] opened 2017-02-20 17:45 UTC
When visiting Survey section base pane, the list can't map the items since there aren't any which results in an exception.

**Comment by richardolsson** [comment] 2017-02-25 15:56
I can't reproduce this. I'm guessing the exception you got was not because the list was empty, but because there was an error on the server (where the survey resources had not yet been deployed at the time). I'm closing this.

For future reports, please include stack traces of the exception, so that we can more easily figure out what exactly went wrong.

**Closed by richardolsson** 2017-02-25 15:56 UTC
Labels: bug
