### ISSUE TITLE
Manual merge of duplicates

### ISSUE THREAD

**Issue by niklasva82** [zetkin/organize.zetk.in#1045] opened 2020-02-13 10:43 UTC
It should be possible to manually merge two people outside the duplicate search feature. This can likely be accomplished inserting a PersonCollection component in the Duplicate tab of manage to select an optional number of people and calling the merge API endpoint from there.

**Comment by richardolsson** [comment] 2020-10-24 07:21
Duplicate of #803. Keeping this.

**Closed** 2020-10-24 07:21 UTC
